### ISSUE TITLE
Cannot create a container with installed node_modules inside a container.

### ISSUE THREAD

**Issue by ablesable** [ablesable/DevopsRecap#13]
$ docker run --init --rm --publish 3000:3000 my-bigger-node-app 
/home/node/code/node_modules/@hapi/hapi/lib/server.js:103
        this._core.controlled = this._core.controlled ?? [];
                                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/node/code/node_modules/@hapi/hapi/lib/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)`

**Comment by ablesable** [comment]
Delete `npm ci`, and replace it with `npm install` in a dockerfile. 
Delete package-lock.json file,  npm install will install node_package inside of a container from package.json anyway.
MOST important! Change the versions of @hapi/hapi and hapi-pino to ^18.4.0 and ^6.3.0 respectively. THAT was the main problem.
